import Head from 'next/head'

export default function Home() {
  return (
    <div className="bg-red-400">
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="">
            <h1>Home page</h1>
        </main>
    </div>
  )
}